name: Keep Supabase Active

on:
  schedule:
    # Runs every 6 days at 2:00 AM UTC (before the 7-day pause threshold)
    - cron: '0 2 */6 * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Simple query to keep the database active
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/ping" \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H "Content-Type: application/json"
          
          echo "Pinged Supabase successfully at $(date)"
